"""
Sets the input current array to represent a baseline input level with
an extra 'lump' in the centre generated by a function of form 1/cosh.
"""

from numba import cuda
from math import pi, e, cosh

from modules import Control
lookup = Control.lookup

neurons_number = lookup["neurons_number"]

input_base_before = lookup["input_base_before"]
rc_height = lookup["rc_height"]
rc_narrow = lookup["rc_narrow"]

@cuda.jit()
def input_init(input_strength_d, coordinates_d):
    """
    Initialises input_strength array with a base value added to a 1/cosh curve.
    """
    n = cuda.grid(1)
    if n < neurons_number:
        position = Control.d.get_distance_from_centre(coordinates_d, n)
        strength = input_base_before + rc_height / cosh(rc_narrow * position)
        input_strength_d[n] = strength
